In [ ]:
Задание 0
Придумайте матрицы, которые обладают следующими свойствами:
a) диагональная, ортогональная, но не единичная(!):
b) верхнетреугольная, ортогональная:
c) нижнетреугольная, ортогональная:
d) матрица, у которой определитель = 1, и все элементы не равны 0:
P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

In [2]:
import numpy as np

In [3]:
# диагональная, ортогональная, но не единичная(!)
# верхнетреугольная, ортогональная
# нижнетреугольная, ортогональная

In [4]:
m = np.array([[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1],])
print(m)


[[-1  0  0  0]
 [ 0  1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]


In [5]:
w = m.transpose()
R = m @ w
print(R)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [8]:
# матрица, у которой определитель = 1, и все элементы не равны 0

In [6]:
vw = np.array([[1, 2], [-1, -1]])
print(vw)

[[ 1  2]
 [-1 -1]]


In [7]:
#определитель = 1
np.linalg.det(vw)

1.0

In [ ]:
Найдите собственные значения и собственные вектора матриц:
m = np.array([[2, 2],
[1, 3]])
print(m)

In [8]:
we = np.array([[2, 2],
[1, 3]])
print(we)

[[2 2]
 [1 3]]


In [10]:
wr, vr = np.linalg.eig(we)

In [11]:
for i in range(len(wr)):
    print("Собственное значение " + str(wr[i]))
    print("соответствующий ему собственный вектор " + str(vr[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


In [13]:
Задание 2
#Найдите спектральное разложение матрицы:
me = np.array([[1, 2],
[2,3]])
print(me)

[[1 2]
 [2 3]]


In [14]:
a, S = np.linalg.eig(me)

print('Собственные значения:')
print(np.array(a, dtype=float))
print('\nСобственные вектора:')
print(S)

Собственные значения:
[-0.23606798  4.23606798]

Собственные вектора:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
